/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AuctionState {
  'currentPlayerIndex' : bigint,
  'isActive' : boolean,
  'currentBidderId' : [] | [bigint],
  'currentBid' : bigint,
}
export interface Team {
  'id' : bigint,
  'impactPlayerId' : [] | [bigint],
  'isAI' : boolean,
  'name' : string,
  'playingXI' : Array<bigint>,
  'squad' : Array<bigint>,
  'budget' : bigint,
}
export interface _SERVICE {
  'getAuctionState' : ActorMethod<[], AuctionState>,
  'getSquad' : ActorMethod<[bigint], Array<bigint>>,
  'getTeam' : ActorMethod<[bigint], Team>,
  'passPlayer' : ActorMethod<[], undefined>,
  'placeBid' : ActorMethod<[bigint, bigint], undefined>,
  'setImpactPlayer' : ActorMethod<[bigint, bigint], undefined>,
  'setPlayingXI' : ActorMethod<[bigint, Array<bigint>], undefined>,
  'startAuction' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];