/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AuctionState = IDL.Record({
  'currentPlayerIndex' : IDL.Nat,
  'isActive' : IDL.Bool,
  'currentBidderId' : IDL.Opt(IDL.Nat),
  'currentBid' : IDL.Nat,
});
export const Team = IDL.Record({
  'id' : IDL.Nat,
  'impactPlayerId' : IDL.Opt(IDL.Nat),
  'isAI' : IDL.Bool,
  'name' : IDL.Text,
  'playingXI' : IDL.Vec(IDL.Nat),
  'squad' : IDL.Vec(IDL.Nat),
  'budget' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getAuctionState' : IDL.Func([], [AuctionState], ['query']),
  'getSquad' : IDL.Func([IDL.Nat], [IDL.Vec(IDL.Nat)], ['query']),
  'getTeam' : IDL.Func([IDL.Nat], [Team], ['query']),
  'passPlayer' : IDL.Func([], [], []),
  'placeBid' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'setImpactPlayer' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'setPlayingXI' : IDL.Func([IDL.Nat, IDL.Vec(IDL.Nat)], [], []),
  'startAuction' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AuctionState = IDL.Record({
    'currentPlayerIndex' : IDL.Nat,
    'isActive' : IDL.Bool,
    'currentBidderId' : IDL.Opt(IDL.Nat),
    'currentBid' : IDL.Nat,
  });
  const Team = IDL.Record({
    'id' : IDL.Nat,
    'impactPlayerId' : IDL.Opt(IDL.Nat),
    'isAI' : IDL.Bool,
    'name' : IDL.Text,
    'playingXI' : IDL.Vec(IDL.Nat),
    'squad' : IDL.Vec(IDL.Nat),
    'budget' : IDL.Nat,
  });
  
  return IDL.Service({
    'getAuctionState' : IDL.Func([], [AuctionState], ['query']),
    'getSquad' : IDL.Func([IDL.Nat], [IDL.Vec(IDL.Nat)], ['query']),
    'getTeam' : IDL.Func([IDL.Nat], [Team], ['query']),
    'passPlayer' : IDL.Func([], [], []),
    'placeBid' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'setImpactPlayer' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'setPlayingXI' : IDL.Func([IDL.Nat, IDL.Vec(IDL.Nat)], [], []),
    'startAuction' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };