/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface AuctionState {
    currentPlayerIndex: bigint;
    isActive: boolean;
    currentBidderId?: bigint;
    currentBid: bigint;
}
export interface Team {
    id: bigint;
    impactPlayerId?: bigint;
    isAI: boolean;
    name: string;
    playingXI: Array<bigint>;
    squad: Array<bigint>;
    budget: bigint;
}
export interface backendInterface {
    getAuctionState(): Promise<AuctionState>;
    getSquad(teamId: bigint): Promise<Array<bigint>>;
    getTeam(teamId: bigint): Promise<Team>;
    passPlayer(): Promise<void>;
    placeBid(teamId: bigint, amount: bigint): Promise<void>;
    setImpactPlayer(teamId: bigint, playerId: bigint): Promise<void>;
    setPlayingXI(teamId: bigint, playerIds: Array<bigint>): Promise<void>;
    startAuction(): Promise<void>;
}
import type { AuctionState as _AuctionState, Team as _Team } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getAuctionState(): Promise<AuctionState> {
        if (this.processError) {
            try {
                const result = await this.actor.getAuctionState();
                return from_candid_AuctionState_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAuctionState();
            return from_candid_AuctionState_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSquad(arg0: bigint): Promise<Array<bigint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSquad(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSquad(arg0);
            return result;
        }
    }
    async getTeam(arg0: bigint): Promise<Team> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeam(arg0);
                return from_candid_Team_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTeam(arg0);
            return from_candid_Team_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async passPlayer(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.passPlayer();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.passPlayer();
            return result;
        }
    }
    async placeBid(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.placeBid(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeBid(arg0, arg1);
            return result;
        }
    }
    async setImpactPlayer(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setImpactPlayer(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setImpactPlayer(arg0, arg1);
            return result;
        }
    }
    async setPlayingXI(arg0: bigint, arg1: Array<bigint>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setPlayingXI(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setPlayingXI(arg0, arg1);
            return result;
        }
    }
    async startAuction(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.startAuction();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startAuction();
            return result;
        }
    }
}
function from_candid_AuctionState_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AuctionState): AuctionState {
    return from_candid_record_n2(_uploadFile, _downloadFile, value);
}
function from_candid_Team_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Team): Team {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    currentPlayerIndex: bigint;
    isActive: boolean;
    currentBidderId: [] | [bigint];
    currentBid: bigint;
}): {
    currentPlayerIndex: bigint;
    isActive: boolean;
    currentBidderId?: bigint;
    currentBid: bigint;
} {
    return {
        currentPlayerIndex: value.currentPlayerIndex,
        isActive: value.isActive,
        currentBidderId: record_opt_to_undefined(from_candid_opt_n3(_uploadFile, _downloadFile, value.currentBidderId)),
        currentBid: value.currentBid
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    impactPlayerId: [] | [bigint];
    isAI: boolean;
    name: string;
    playingXI: Array<bigint>;
    squad: Array<bigint>;
    budget: bigint;
}): {
    id: bigint;
    impactPlayerId?: bigint;
    isAI: boolean;
    name: string;
    playingXI: Array<bigint>;
    squad: Array<bigint>;
    budget: bigint;
} {
    return {
        id: value.id,
        impactPlayerId: record_opt_to_undefined(from_candid_opt_n3(_uploadFile, _downloadFile, value.impactPlayerId)),
        isAI: value.isAI,
        name: value.name,
        playingXI: value.playingXI,
        squad: value.squad,
        budget: value.budget
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
